version: '3.9'
services:
  db:
    image: postgres:13
    volumes:
      - ./data/db:/lib/postgresql/data/
    environment:
      - POSGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - static_vol:/code/sub_app/static
      - media_vol:/code/sub_app/media
      - .:/code
    ports:
      - 8000:8000
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  nginx:
    build: ./nginx
    volumes:
        - static_vol:/code/sub_app/static
        - media_vol:/code/sub_app/media
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  static_vol:
  media_vol:
