# Generated by Django 4.0 on 2022-11-18 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id_vehiculo', models.BigAutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=10, unique=True)),
                ('modelo', models.TextField()),
                ('aseguramiento', models.CharField(choices=[('PT', 'Perdida total'), ('DC', 'Daños colaterales'), ('DP', 'Daños parciales')], max_length=2)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
