# Generated by Django 4.0 on 2022-12-13 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0005_uuidmodel_remove_incidente_id_incidente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidente',
            name='modelo',
        ),
    ]
