# Generated by Django 4.0 on 2022-12-13 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_alter_vehiculo_modelo_alter_vehiculo_uuidmodel_ptr'),
        ('incidentes', '0006_remove_incidente_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vehiculo'),
            preserve_default=False,
        ),
    ]
