# Generated by Django 4.0 on 2022-12-13 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0007_incidente_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='comentarios',
            field=models.TextField(default=''),
        ),
    ]
