# Generated by Django 4.0 on 2022-12-13 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.BigAutoField(primary_key=True, serialize=False)),
                ('modelo', models.TextField()),
            ],
        ),
    ]
