# Generated by Django 4.0 on 2022-12-13 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_uuidmodel_remove_vehiculo_id_vehiculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.TextField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='uuidmodel_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='vehiculos.uuidmodel'),
        ),
    ]
