# Generated by Django 4.0 on 2022-12-13 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_alter_vehiculo_modelo_alter_vehiculo_uuidmodel_ptr'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='año',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
