# Generated by Django 4.0 on 2022-12-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_vehiculo_año'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='marca',
            field=models.TextField(default=''),
        ),
    ]
