# Generated by Django 4.0 on 2022-12-13 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0005_vehiculo_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='año',
            field=models.IntegerField(default=1990),
        ),
    ]
