# Generated by Django 4.0 on 2022-12-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0006_alter_vehiculo_año'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='url_imagen',
            field=models.TextField(default=''),
        ),
    ]
